import jsPDF from "jspdf";
// jspdf-autotable v5 no longer patches the jsPDF prototype — it exports a
// function taking the document as its first argument.
import autoTable from "jspdf-autotable";

const BRAND = [58, 52, 212];
const INK = [15, 20, 36];
const MUTED = [110, 118, 140];

const inr = (n) => `Rs. ${Number(n || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const kg = (n) => `${Number(n || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 })} kg`;
const dmy = (d) => new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

export const generateCpcbReport = (report) => {
  const doc = new jsPDF();
  const { meta, summary, categoryBreakdown, regionBreakdown, traceability, destinationStatus } = report;

  // --- header ---
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, 210, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.text("E-WASTE CHANNELIZATION REPORT", 105, 14, { align: "center" });
  doc.setFontSize(8.5);
  doc.text("Submitted for CPCB / SPCB review under E-Waste (Management) Rules, 2022", 105, 21, { align: "center" });
  doc.text("Generated by Kabadiwala Connect - Informal Collector Formalization Platform", 105, 27, { align: "center" });

  // --- report meta ---
  let y = 44;
  doc.setTextColor(...INK);
  doc.setFontSize(9);
  doc.text(`Report ID:`, 14, y);
  doc.text(`Reporting Period:`, 14, y + 6);
  doc.text(`Region:`, 14, y + 12);
  doc.text(`Generated On:`, 14, y + 18);

  doc.setFont(undefined, "bold");
  doc.text(meta.reportId, 48, y);
  doc.text(`${dmy(meta.period.from)}  to  ${dmy(meta.period.to)}`, 48, y + 6);
  doc.text(meta.region === "all" ? "All regions" : meta.region, 48, y + 12);
  doc.text(dmy(meta.generatedAt), 48, y + 18);
  doc.setFont(undefined, "normal");

  // --- headline figures ---
  y += 30;
  doc.setFillColor(245, 246, 250);
  doc.roundedRect(14, y, 182, 26, 2, 2, "F");

  const tiles = [
    ["Total Channelized", `${summary.totalWeightTonnes} MT`],
    ["Consignments", String(summary.consignments)],
    ["Active Collectors", String(summary.activeCollectors)],
    ["Traceability Score", `${summary.traceabilityScore}%`],
  ];
  tiles.forEach(([label, value], i) => {
    const x = 14 + 45.5 * i + 22.75;
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(label, x, y + 9, { align: "center" });
    doc.setFontSize(13);
    doc.setTextColor(...BRAND);
    doc.setFont(undefined, "bold");
    doc.text(value, x, y + 19, { align: "center" });
    doc.setFont(undefined, "normal");
  });

  // --- category table ---
  y += 34;
  doc.setTextColor(...INK);
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text("1. Category-wise Channelization", 14, y);
  doc.setFont(undefined, "normal");

  autoTable(doc, {
    startY: y + 4,
    head: [["Material Category", "Weight", "Share", "Consignments", "Recorded Value"]],
    body: categoryBreakdown.map((c) => [c.label, kg(c.weight), `${c.share}%`, String(c.consignments), inr(c.value)]),
    foot: [["TOTAL", kg(summary.totalWeightKg), "100%", String(summary.consignments), inr(summary.totalValue)]],
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8.5 },
    footStyles: { fillColor: [241, 243, 249], textColor: INK, fontStyle: "bold", fontSize: 8.5 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
    theme: "grid",
  });

  // --- region table ---
  y = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text("2. Region-wise Collection", 14, y);
  doc.setFont(undefined, "normal");

  autoTable(doc, {
    startY: y + 4,
    head: [["Region", "Weight", "Share", "Collectors", "Consignments"]],
    body: regionBreakdown.map((r) => [r.region, kg(r.weight), `${r.share}%`, String(r.collectors), String(r.consignments)]),
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8.5 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
    theme: "grid",
  });

  // --- page 2: traceability + destination ---
  doc.addPage();
  y = 20;
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...INK);
  doc.text("3. Traceability Completeness", 14, y);
  doc.setFont(undefined, "normal");

  const traceRows = [
    ["GPS-tagged collection point", traceability.gpsTagged],
    ["Photographic evidence on record", traceability.photoEvidence],
    ["Unique handover reference issued", traceability.uniqueReference],
    ["Confirmed by receiving recycler", traceability.recyclerConfirmed],
    ["Digitally signed handover pass", traceability.digitallySigned],
  ].map(([label, v]) => [label, String(v.count), `${v.pct}%`]);

  autoTable(doc, {
    startY: y + 4,
    head: [["Traceability Attribute", "Records", "Coverage"]],
    body: traceRows,
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8.5 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" } },
    theme: "grid",
  });

  y = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text("4. Downstream Destination Status", 14, y);
  doc.setFont(undefined, "normal");

  autoTable(doc, {
    startY: y + 4,
    head: [["Destination Status", "Consignments", "Share"]],
    body: destinationStatus.map((d) => [d.label, String(d.count), `${d.pct}%`]),
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8.5 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" } },
    theme: "grid",
  });

  // --- participation summary ---
  y = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.text("5. Participation Summary", 14, y);
  doc.setFont(undefined, "normal");

  autoTable(doc, {
    startY: y + 4,
    head: [["Metric", "Value"]],
    body: [
      ["Registered collectors on platform", String(summary.registeredCollectors)],
      ["Collectors active in this period", String(summary.activeCollectors)],
      ["Authorized recyclers on platform", String(summary.authorizedRecyclers)],
      ["Recyclers engaged in this period", String(summary.engagedRecyclers)],
      ["Consignments to authorized recyclers", `${summary.authorizedChannelPct}%`],
      ["Records with complete audit trail", `${summary.completeRecords} (${summary.traceabilityScore}%)`],
    ],
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontSize: 8.5 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right" } },
    theme: "grid",
  });

  // --- declaration ---
  y = doc.lastAutoTable.finalY + 12;
  doc.setFillColor(245, 246, 250);
  doc.roundedRect(14, y, 182, 30, 2, 2, "F");
  doc.setFontSize(8.5);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...INK);
  doc.text("Declaration", 19, y + 7);
  doc.setFont(undefined, "normal");
  doc.setTextColor(...MUTED);
  doc.setFontSize(7.5);
  doc.text(
    doc.splitTextToSize(
      `This report is generated from platform-recorded consignments between registered informal collectors and authorized recyclers. Each consignment carries a unique handover reference, GPS coordinates and a timestamp captured at the point of collection. Figures are derived from ${summary.consignments} recorded consignments over the stated period and are reported on the basis of ${meta.basis.toLowerCase()}. Reference: ${meta.ruleReference}.`,
      172
    ),
    19,
    y + 13
  );

  // --- footers ---
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(`${meta.reportId}`, 14, 289);
    doc.text(`Page ${p} of ${pages}`, 196, 289, { align: "right" });
    doc.text("Kabadiwala Connect - SIH 2026 PS 26229 - Ministry of Mines", 105, 289, { align: "center" });
  }

  doc.save(`${meta.reportId}.pdf`);
};
