import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateInvoice = (transaction, user) => {
  const doc = new jsPDF();
  const brand = [58, 52, 212]; // #3A34D4

  doc.setFillColor(...brand);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("KABADIWALA CONNECT", 105, 18, { align: "center" });
  doc.setFontSize(10);
  doc.text("Verified Scrap Transaction Invoice", 105, 28, { align: "center" });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  const y = 50;
  doc.text(`Invoice Date: ${new Date(transaction.date || transaction.created_at || Date.now()).toLocaleDateString("en-IN")}`, 14, y);
  doc.text(`Reference: ${transaction.handoverRef || transaction.handover_ref || "—"}`, 14, y + 7);
  doc.text(`Status: ${transaction.status || "Completed"}`, 14, y + 14);

  doc.setFontSize(11);
  doc.setTextColor(...brand);
  doc.text("Seller (Collector)", 14, y + 28);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Name: ${user?.name || "—"}`, 14, y + 35);
  doc.text(`Phone: ${user?.phone || "—"}`, 14, y + 42);

  doc.setTextColor(...brand);
  doc.setFontSize(11);
  doc.text("Buyer (Recycler)", 110, y + 28);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Name: ${transaction.recyclerName || "Authorized Recycler"}`, 110, y + 35);

  const tableData = [[
    transaction.materialName || "Scrap lot",
    `${transaction.weightKg || 0} kg`,
    `₹${transaction.pricePerKg || 0}/kg`,
    `₹${transaction.totalAmount || 0}`
  ]];

  autoTable(doc, {
    startY: y + 52,
    head: [["Material", "Weight", "Rate", "Amount"]],
    body: tableData,
    headStyles: { fillColor: brand, textColor: [255, 255, 255] },
    styles: { fontSize: 10 },
    theme: "grid"
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setTextColor(...brand);
  doc.text(`Total: ₹${transaction.totalAmount || 0}`, 195, finalY, { align: "right" });

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(8);
  doc.text("This invoice was generated by Kabadiwala Connect — verified formal recycling.", 105, 280, { align: "center" });

  doc.save(`Kabadiwala_Invoice_${transaction.handoverRef || transaction.id || "receipt"}.pdf`);
};
